---
abstract: 'framework for ease development/deploy/support for medium/big projects'
author:
  - 'Alex Efros <powerman@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Narada
provides:
  Narada:
    file: lib/Narada.pm
    version: v1.3.4
  Narada::Config:
    file: lib/Narada/Config.pm
    version: v1.3.4
  Narada::Lock:
    file: lib/Narada/Lock.pm
    version: v1.3.4
  Narada::Log:
    file: lib/Narada/Log.pm
    version: v1.3.4
requires:
  DBD::mysql: 0
  DBI: 0
  FindBin: 0
  Log::Fast: 0
  MIME::Base64: 0
  Perl6::Export::Attrs: 0
  perl: v5.10.0
  version: 0.77
resources:
  license: http://dev.perl.org/licenses/
version: v1.3.4
