---
abstract: 'framework for ease development/deploy/support for medium/big projects'
author:
  - 'Alex Efros <powerman@cpan.org>'
build_requires:
  Pod::Coverage: '0.18'
  Test::CheckManifest: '0.9'
  Test::Differences: '0'
  Test::Exception: '0'
  Test::MockModule: '0'
  Test::Perl::Critic: '0'
  Test::Pod: '1.22'
  Test::Pod::Coverage: '1.08'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Narada
provides:
  Narada:
    file: lib/Narada.pm
    version: v1.3.12
  Narada::Config:
    file: lib/Narada/Config.pm
    version: v1.3.11
  Narada::Lock:
    file: lib/Narada/Lock.pm
    version: v1.3.11
  Narada::Log:
    file: lib/Narada/Log.pm
    version: v1.3.11
requires:
  DBD::mysql: '0'
  DBI: '0'
  FindBin: '0'
  Log::Fast: '0'
  MIME::Base64: '0'
  Perl6::Export::Attrs: '0'
  perl: '5.01'
  version: '0.77'
resources:
  license: http://dev.perl.org/licenses/
version: v1.3.12
